// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('New Test', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('New Test', async function() {
    await driver.get("http://www.google.com/")
{
  const element = await driver.findElement(By.css(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)"))
  await driver.actions({ bridge: true }).moveToElement(element).perform()
}
await driver.findElement(By.css(".MjjYud:nth-child(3) .LC20lb")).click()
  })
})
